### ISSUE TITLE
Change of behavior for the compare function

### ISSUE THREAD

**Issue by MaxGfeller** [MaxGfeller/array-patch#1]
Currently the `compare` function, as described [here](https://github.com/MaxGfeller/array-patch#the-compare-function), takes the last entry in a list of candidates.

This behavior is not that well to work with and should be changed to the following:
- The `compare` function should return a numerical value instead of a boolean
- The chosen candidate should be the one with the highest value

Comparing for similiarity should become way easier this way. Also, the docs and tests should be updated accordingly.

**Comment by lucas-carl** [comment]
hey, @MaxGfeller, I would like to work on this!

**Comment by MaxGfeller** [comment]
Perfect, @lucas-carl! Just let me know when you have any questions.

**Comment by lucas-carl** [comment]
Hey @MaxGfeller, what do you exactly mean when you say the compare function should return a numerical value?

**Comment by MaxGfeller** [comment]
@lucas-carl So instead of a boolean value the user-provided compare function should just return any number. I wouldn't make any preconditions of what the number must look like but in the end we should just pick the candidate with the highest number.

For a text array we could do the following then:

```javascript
var { createPatch } = require('array-patch')
var similarity = require('similarity')

var arr1 = ['foo', 'bar', 'baz']
var arr2 = ['foo', 'blub', 'bar1', 'baz']

var patch = createPatch(arr1, arr2, similarity)
```
